### ISSUE TITLE
预训练结束之后，报以下问题

### ISSUE THREAD

**Issue by shylie728** [Neverland610/MSUDA_REID#1]
![image](https://user-images.githubusercontent.com/101248412/171130448-54bc32a6-bf88-495d-a1e5-6638de3bc0d0.png)

预训练结束之后，进行端到端训练的时候报以上的错误，请问是你给的预训练模型有问题吗，还有一个mismatch的问题。

**Comment by Neverland610** [comment]
To debug, you should follow the Traceback.
According to your screenshot, the problem occurs in [line 87 of rdsbn.py](https://github.com/Neverland610/MSUDA_REID/blob/b12cf3cc41d73b147253bd0302c6b645ff4494fb/mmt/models/rdsbn.py#L87)
So the problem is that you probably set a mis-matched batch size or the dataset problem.
Note that this code of adaptation is written to run on 3 source datasets and 1 target dataset, in which each dataset occupy a batch size of 16.
You can change the setting accordingly.
